language: go
sudo: required
services:
- docker
notifications:
  slack:
    secure: VuZvwLTu7AJH4M3Lk5Othi+Fa7XWQ8sDj0VVVfkXuMVNrOrFKyvRhuFrEa0XOvRyJaul6v1TlRV3SmncEu+6s6UCHMt3JQjnc9X9fbfIX1Mx2LL1Sjtfm0Lp6YdZvuTixd0eH2qCuj5rCbPakm2qLxpLzGxzjRM96Uxc4pqs2ibilB2tXEhJ31kRfIwO3R5gIvZRYm7y2CJWvcV1Jxe1p1HMyDKxhPgM/H8MdNTQdhBZOAo6RDqJm/bwHiHc7/N05H7TkDggnqszWkhjvAXC25zhEv9qlG1YyMnTxnyAwib/PFU5ANLXgHERO2llIhz520eiH05yRGvl2ZWtTPl5UMP4KGlqEQ0pwpEKe0PnqCISUfXVIG7itJNukupzh3+T91cvHQLMH0vcw7d2acViZo/n2VEJkggg2HBGNWnu3lX4HHpHicrLlAPUXjl8nzwteA5PybLsPKQegPQ5jg6Fl0OffREyOBETHGY5FCHKAe3mtjbMgFVnrGTZSe8ss4YqDCXd45/aDLVBkxFf9AXqC/bfR1Z9iboHTGfIHLc6Bta8u7QyK1fwqgoXBpT++37RdXQNFPY8JQPJcm6SpvYQ0kvtmjK9ez3ETlmBUepLs39Z2YsbwZbOjwuQQUf/5CjBEdS48vdhACERzBiAOZ2PipJDCNf7vcW1Pn4PMojktRc=
