language: go
sudo: required
services:
- docker
notifications:
  slack:
    rooms:
      secure: seVd0ZqpvFZ3/Q4FxRp83ocQSXP7STXKG5dYXb7QP1Gl2MBh4dUVdy4YWJuMysxzzuYgb8YZkoGKhGGOMZ8dXhTXzP6aCCeYHGizrg5VmwP4FtV0hUzasMUVpNgoyV14UnHYkMvqHL5kUsedh4FHtIXhN6LapT2edU8SkHxPNIeCrPmrzztr5ty+fJznDoF8vIWge/b9bgGxvsdgLyKc8g9PcnNSlQpvTv7ElXn0tQR6x01qDCAe6tJMB4YC9ebJPSrE2tXMK1uvL1ebtgWpC1D117lXtoOvlaX2Q+3bJxN3TOkkIldyiEGzokXvvCPoCaezFvVhfWT5ujM/CDPKfdBHFiyZy2/ZeXplxya3AcH5yVsV0X5B90T6j6zgIj6oIJMV0iprCd+0NBbZW5lxk47hrrJ+gjp09YMwcu7XIBkfkU+zRt7kkTUp+TQDWU9sTYNSiM9KHv60+a/jR5s6Sl7Fc3736QuGEg8PWV9iaMBAHtNkEHUu/0KHFWxfIjOjrnZWKy1nwsmprRlGM3je8J8L8VCc0cG2Sm+nN1xweX1E2w67k6wmJRmR+Qv9JL8v1x9MPHagkKDGhnzVag7ffzbSBvupbfnAdrci2qz/5/aimBKKUxmkYOSvk42yC1ZOMjI9offMckU9M2lcxJptoTGgZ/d+AwEgY5xsUutyVHM=
