language: go
sudo: required
services:
- docker
notifications:
  slack:
    rooms:
      secure: dRJ40eIGs0VUrZq3Gw87OzsdEVvjEAMU2KgdWe8D8nr284ZuMlwkMLVUJzBZF7MrM+TiDTDeHZxu6MH++0kReUqXlVcDKYoUO5AFL46OCCUBDbfr0sSDVXWy4azvl1CZ1NohU9jMMszCv9QltMcvZld90NwbqNHqgVnybeFGcSbRakZOdGr0XK4itmkeyT5Ezkjbr/hY7JVa2Qzxz8s9Da/EANp30j9Jc4rH127caTe7jh4Gy10maw3xhFolOJyaf6MSk1w5RmKFoaQ2xeiKJZn6hYqX4QbDTSE3Z+/qMGZceLi5n2KdBFVv8a/2jyfwA5Jv9OQKMVbVobjgIXVIlpd4B5Wu3yMVRkO4ikDT5tzzk6CW9Eshphi74s0HHCwInG5ecjPSi4Ne6ldQ42Eg5f45tGy2oLBfQXRaz2h9FCMZkwJzdLrN/0LAj748QmxvTUEuv5PLF9lyjj2HIMg1ui9avv07iTImsjKp9Lk2UHklDZpsytFE3aX44LMVIuBiyqta+sFrOKw2qs4pazzyg8XjOuc94+YhJjhsrWqmICeKaL5uRZBr4oZe6WR/+qfU8i1+PNyp4496FVAZT7A7PDaP/QHDejpKKOTCC2POyFuwYYc69zSG9Q5K/eQ9dt0VvQUZl6qerIdB2ZVPptNafB+1ZOHOQAb/ZFVrwdm5Vmc=
